### ISSUE TITLE
webpack webpack-dev-server 分别用的哪个版本？

### ISSUE THREAD

**Issue by Jamelzhou** [yujinjin/fans#24]
我用的node版本v10.15.1, npm版本v6.4.1
按照配置文件里面webpack的版本执行如下安装命令：
npm install webpack@2.1.0-beta.25
npm i webpack-dev-server@2.1.0-beta.10
然后，启动npm run R_DEV出下面错。请问大神使用哪个webpack和webpack-dev-server版本能跑起来？webpack的版本之间兼容性实在太差了，大神最好是在文档里面给予明示。
                throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
                ^
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configu
ration object that does not match the API schema.
 - configuration has an unknown property 'performance'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader
?, module?, name?, node?, output?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath
?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack 2 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: {
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           performance: ...
         }
       })
     }
    at webpack (E:\app\fans\node_modules\webpack\lib\webpack.js:16:9)
    at processOptions (E:\app\fans\node_modules\webpack-dev-server\bin\webpack-dev-server.js:310:17)
    at Object.<anonymous> (E:\app\fans\node_modules\webpack-dev-server\bin\webpack-dev-server.js:374:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

**Comment by Jamelzhou** [comment]
一个一个版本尝试，终于发现webpack 3.5.5  webpack-dev-server 2.7.1可以用。
